version: "3"
services:
  gematrix-backend:
    container_name: gematrix-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: gematrix/gematrix-backend
    stdin_open: true
    tty: true
    volumes:
      - ./gematrix/:/service
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://gematrix:topsecret@db:5432/gematrix_db

  db:
    image: postgres:12-alpine
    container_name: gematrix-psql
    environment:
      - POSTGRES_USER=gematrix
      - POSTGRES_PASSWORD=topsecret
      - POSTGRES_DB=gematrix_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker_volumes/postgresql/data:/var/lib/postgresql/data
