# Generated by Django 2.2.6 on 2019-11-05 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='unique id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('sort', models.IntegerField(blank=True, default=0, verbose_name='номер объекта для сортировки')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='активен ли объект')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
            ],
            options={
                'verbose_name': 'ядро',
                'verbose_name_plural': 'ядра',
                'ordering': ('-time_created',),
            },
        ),
        migrations.CreateModel(
            name='GematrixSource',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Core')),
                ('source_name', models.CharField(default='index', max_length=1024, verbose_name='Адрес сайта')),
            ],
            options={
                'verbose_name': 'Источник данных',
                'verbose_name_plural': 'Источники данных',
            },
            bases=('api.core',),
        ),
        migrations.CreateModel(
            name='GematrixTags',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Core')),
                ('tags_name', models.CharField(blank=True, max_length=128, verbose_name='Tag')),
            ],
            options={
                'ordering': [],
            },
            bases=('api.core',),
        ),
        migrations.CreateModel(
            name='GematrixDatasets',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Core')),
                ('gematrix_tags', models.ManyToManyField(to='api.GematrixTags')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.GematrixSource', verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Датасет',
                'verbose_name_plural': 'Датасеты',
            },
            bases=('api.core',),
        ),
        migrations.CreateModel(
            name='GematrixData',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Core')),
                ('x_data', models.DateField(blank=True, null=True, verbose_name='Период времени')),
                ('y_value', models.SmallIntegerField(blank=True, null=True, verbose_name='Уровень ряда')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GematrixDatasets', verbose_name='Датасет')),
            ],
            options={
                'verbose_name': 'Элемент ряда',
                'verbose_name_plural': 'Элементы ряда',
            },
            bases=('api.core',),
        ),
    ]
