# Generated by Django 2.2.6 on 2019-11-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GematrixData',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Core')),
                ('x_data', models.DateField(blank=True, null=True, verbose_name='Период времени')),
                ('y_value', models.SmallIntegerField(blank=True, null=True, verbose_name='Уровень ряда')),
            ],
            options={
                'verbose_name': 'Элемент ряда',
                'verbose_name_plural': 'Элементы ряда',
            },
            bases=('api.core',),
        ),
        migrations.CreateModel(
            name='GematrixDatasets',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Core')),
            ],
            options={
                'verbose_name': 'Датасет',
                'verbose_name_plural': 'Датасеты',
            },
            bases=('api.core',),
        ),
        migrations.CreateModel(
            name='GematrixSource',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Core')),
                ('source_name', models.CharField(default='index', max_length=1024, verbose_name='Адрес сайта')),
            ],
            options={
                'verbose_name': 'Источник данных',
                'verbose_name_plural': 'Источники данных',
            },
            bases=('api.core',),
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='core_ptr',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='source',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='core_ptr',
        ),
        migrations.AlterModelOptions(
            name='core',
            options={'ordering': ('-time_created',), 'verbose_name': 'ядро', 'verbose_name_plural': 'ядра'},
        ),
        migrations.RenameField(
            model_name='core',
            old_name='created',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='core',
            old_name='updated',
            new_name='time_updated',
        ),
        migrations.RemoveField(
            model_name='core',
            name='title',
        ),
        migrations.AddField(
            model_name='core',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='название'),
        ),
        migrations.DeleteModel(
            name='DataPoint',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.AddField(
            model_name='gematrixdatasets',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.GematrixSource', verbose_name='Источник данных'),
        ),
        migrations.AddField(
            model_name='gematrixdata',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GematrixDatasets', verbose_name='Датасет'),
        ),
    ]
