# Generated by Django 2.2.6 on 2019-11-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gematrixdata',
            old_name='x_data',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='gematrixdata',
            old_name='y_value',
            new_name='value',
        ),
    ]
